import type { Metadata } from "next";
import localFont from "next/font/local";
import { MockInitializer } from "../mocks/MockInitializer";
import "./styles/output.css";
import { initMSW } from "../mocks";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

if (process.env.NEXT_PUBLIC_USE_API_MOCKING === "true") {
  initMSW();
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {process.env.NODE_ENV === "development" && <MockInitializer />}
        {children}
      </body>
    </html>
  );
}
