export const TAGS = [
  { id: 1, name: '베이글', categoryId: 1, categoryName: '베이커리' },
  { id: 2, name: '샌드위치 / 핫도그', categoryId: 1, categoryName: '베이커리' },
  { id: 3, name: '프레첼', categoryId: 1, categoryName: '베이커리' },
  { id: 4, name: '도넛', categoryId: 1, categoryName: '베이커리' },
  { id: 5, name: '소금빵', categoryId: 1, categoryName: '베이커리' },
  { id: 6, name: '타르트', categoryId: 1, categoryName: '베이커리' },
  { id: 7, name: '토스트', categoryId: 1, categoryName: '베이커리' },
  { id: 8, name: '크루아상', categoryId: 1, categoryName: '베이커리' },
  { id: 9, name: '파이', categoryId: 1, categoryName: '베이커리' },
  { id: 10, name: '식사빵', categoryId: 1, categoryName: '베이커리' },
  { id: 11, name: '케이크', categoryId: 2, categoryName: '디저트' },
  { id: 12, name: '구움과자', categoryId: 2, categoryName: '디저트' },
  { id: 13, name: '마카롱', categoryId: 2, categoryName: '디저트' },
  { id: 14, name: '브라우니', categoryId: 2, categoryName: '디저트' },
  { id: 15, name: '와플', categoryId: 2, categoryName: '디저트' },
  { id: 16, name: '브런치', categoryId: 2, categoryName: '디저트' },
  { id: 17, name: '초콜릿', categoryId: 2, categoryName: '디저트' },
  { id: 18, name: '푸딩', categoryId: 2, categoryName: '디저트' },
  { id: 19, name: '젤리', categoryId: 2, categoryName: '디저트' },
  { id: 20, name: '사탕', categoryId: 2, categoryName: '디저트' },
  { id: 21, name: '붕어빵', categoryId: 3, categoryName: '전통 간식' },
  { id: 22, name: '꽈배기', categoryId: 3, categoryName: '전통 간식' },
  { id: 23, name: '호두과자', categoryId: 3, categoryName: '전통 간식' },
  { id: 24, name: '호떡', categoryId: 3, categoryName: '전통 간식' },
  { id: 25, name: '떡', categoryId: 3, categoryName: '전통 간식' },
  { id: 26, name: '약과', categoryId: 3, categoryName: '전통 간식' },
  { id: 27, name: '오란다', categoryId: 3, categoryName: '전통 간식' },
  { id: 28, name: '한과', categoryId: 3, categoryName: '전통 간식' },
  { id: 29, name: '개성주악', categoryId: 3, categoryName: '전통 간식' },
  { id: 30, name: '정과', categoryId: 3, categoryName: '전통 간식' },
  {
    id: 31,
    name: '그릭요거트',
    categoryId: 4,
    categoryName: '스페셜/시즌 디저트',
  },
  {
    id: 32,
    name: '아이스크림',
    categoryId: 4,
    categoryName: '스페셜/시즌 디저트',
  },
  { id: 33, name: '빙수', categoryId: 4, categoryName: '스페셜/시즌 디저트' },
  { id: 34, name: '파르페', categoryId: 4, categoryName: '스페셜/시즌 디저트' },
  {
    id: 35,
    name: '퓨전 디저트',
    categoryId: 4,
    categoryName: '스페셜/시즌 디저트',
  },
  {
    id: 36,
    name: '시즌 디저트',
    categoryId: 4,
    categoryName: '스페셜/시즌 디저트',
  },
  {
    id: 37,
    name: '건강 디저트',
    categoryId: 4,
    categoryName: '스페셜/시즌 디저트',
  },
  {
    id: 38,
    name: '월드 디저트',
    categoryId: 4,
    categoryName: '스페셜/시즌 디저트',
  },
  {
    id: 39,
    name: '커스텀 디저트',
    categoryId: 4,
    categoryName: '스페셜/시즌 디저트',
  },
  {
    id: 40,
    name: '지역 특산 디저트',
    categoryId: 4,
    categoryName: '스페셜/시즌 디저트',
  },
];
