export const TAG_CATEGORIES = [
  {
    categoryId: 1,
    categoryName: '베이커리',
    emoji: 'https://abs.twimg.com/emoji/v2/svg/1f35e.svg',
    alt: '🍞',
  },
  {
    categoryId: 2,
    categoryName: '디저트',
    emoji: 'https://abs.twimg.com/emoji/v2/svg/1f370.svg',
    alt: '🍰',
  },
  {
    categoryId: 3,
    categoryName: '전통간식',
    emoji: 'https://abs.twimg.com/emoji/v2/svg/1f361.svg',
    alt: '🍡',
  },
  {
    categoryId: 4,
    categoryName: '스페셜/시즌 디저트',
    emoji: 'https://abs.twimg.com/emoji/v2/svg/1f9c1.svg',
    alt: '🧁',
  },
];

export const TAGS = [
  { id: 1, name: '베이글', parentId: 1 },
  { id: 2, name: '샌드위치 / 핫도그', parentId: 1 },
  { id: 3, name: '프레첼', parentId: 1 },
  { id: 4, name: '도넛', parentId: 1 },
  { id: 5, name: '소금빵', parentId: 1 },
  { id: 6, name: '타르트', parentId: 1 },
  { id: 7, name: '토스트', parentId: 1 },
  { id: 8, name: '크루아상', parentId: 1 },
  { id: 9, name: '파이', parentId: 1 },
  { id: 10, name: '식사빵', parentId: 1 },
  { id: 11, name: '케이크', parentId: 2 },
  { id: 12, name: '구움과자', parentId: 2 },
  { id: 13, name: '마카롱', parentId: 2 },
  { id: 14, name: '브라우니', parentId: 2 },
  { id: 15, name: '와플', parentId: 2 },
  { id: 16, name: '브런치', parentId: 2 },
  { id: 17, name: '초콜릿', parentId: 2 },
  { id: 18, name: '푸딩', parentId: 2 },
  { id: 19, name: '젤리', parentId: 2 },
  { id: 20, name: '사탕', parentId: 2 },
  { id: 21, name: '붕어빵', parentId: 3 },
  { id: 22, name: '꽈배기', parentId: 3 },
  { id: 23, name: '호두과자', parentId: 3 },
  { id: 24, name: '호떡', parentId: 3 },
  { id: 25, name: '떡', parentId: 3 },
  { id: 26, name: '약과', parentId: 3 },
  { id: 27, name: '오란다', parentId: 3 },
  { id: 28, name: '한과', parentId: 3 },
  { id: 29, name: '개성주악', parentId: 3 },
  { id: 30, name: '정과', parentId: 3 },
  {
    id: 31,
    name: '그릭요거트',
    parentId: 4,
  },
  {
    id: 32,
    name: '아이스크림',
    parentId: 4,
  },
  { id: 33, name: '빙수', parentId: 4 },
  { id: 34, name: '파르페', parentId: 4 },
  {
    id: 35,
    name: '퓨전 디저트',
    parentId: 4,
  },
  {
    id: 36,
    name: '시즌 디저트',
    parentId: 4,
  },
  {
    id: 37,
    name: '건강 디저트',
    parentId: 4,
  },
  {
    id: 38,
    name: '월드 디저트',
    parentId: 4,
  },
  {
    id: 39,
    name: '커스텀 디저트',
    parentId: 4,
  },
  {
    id: 40,
    name: '지역 특산 디저트',
    parentId: 4,
  },
];
